KD-8 Swagger-Ui-Documentation
KingsWay-Media/nest-backend-boilerplate pull request #4
Opened 2022-08-18 21:21 UTC by ChuloWay

2022-08-19 02:47 UTC, tricelex requested changes
There's something wrong with your folder structure.
Why is the user model outside the user directory? And why have nested user directory?
Please fix your folder structure, everything User should be in one directory.

2022-08-19 02:51 UTC, tricelex reviewed
fix those then send again

2022-08-19 02:51 UTC, tricelex commented on src/model/user.schema.ts
> +    })
Please make your description uniform, check your cases

2022-08-19 09:58 UTC, ChuloWay commented
Okay

2022-08-19 13:18 UTC, tricelex commented on src/main.ts
> +  // app.useGlobalPipes(new ValidationPipe());
remove comment

2022-08-19 13:41 UTC, ChuloWay commented on src/main.ts
> +  // app.useGlobalPipes(new ValidationPipe());
Okay, just seeing it now

2022-08-20 12:09 UTC, tricelex requested changes

2022-08-20 12:09 UTC, tricelex commented on src/main.ts
> +  // app.useGlobalPipes(new ValidationPipe());
what is this nah?

2022-08-20 17:05 UTC, tricelex approved these changes

2022-08-20 17:06 UTC, merged